table DimEmployee
	lineageTag: 7667b19b-984c-42c2-9312-26f656ff134e

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 6e011e5e-1004-447a-a620-cab1d71aed23
		summarizeBy: count
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = Automatic

	column ParentEmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 7cd6b713-7b09-4d5c-b522-7c6312e1a4f1
		summarizeBy: count
		sourceColumn: ParentEmployeeKey

		annotation SummarizationSetBy = Automatic

	column EmployeeNationalIDAlternateKey
		dataType: string
		lineageTag: a7cd3260-491d-4f8c-aa6b-167869c2ce98
		summarizeBy: none
		sourceColumn: EmployeeNationalIDAlternateKey

		annotation SummarizationSetBy = Automatic

	column ParentEmployeeNationalIDAlternateKey
		dataType: string
		lineageTag: 269b5868-d799-4fe4-9cec-0a5eb7d587aa
		summarizeBy: none
		sourceColumn: ParentEmployeeNationalIDAlternateKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 2a0721d2-1408-446a-af48-3cb7eb435b5e
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: bcbd3457-5031-4b89-8c4b-5e303b7a62b9
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 0bfe76c5-d064-45d4-94f0-c00cdd57efce
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column MiddleName
		dataType: string
		lineageTag: e8031417-e7a5-4159-b426-15521f5ea077
		summarizeBy: none
		sourceColumn: MiddleName

		annotation SummarizationSetBy = Automatic

	column NameStyle
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 07d2b6b9-6e12-4fb1-922b-fa11a9eb1d56
		summarizeBy: none
		sourceColumn: NameStyle

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: ce7d7d29-c870-4613-a696-9a5958a1066d
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 27f57893-9d1c-44f5-b39f-d3232415917d
		summarizeBy: none
		sourceColumn: HireDate

		variation Variation
			isDefault
			relationship: 04343d47-3cb5-4470-81d5-897b2b59ef8f
			defaultHierarchy: LocalDateTable_07f29d46-ba4c-4199-b594-83773787616b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d938ac4-785f-45b6-b660-b685bf0f849a
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variation
			isDefault
			relationship: 57c55149-6889-4858-8edc-af0f8e2c4e47
			defaultHierarchy: LocalDateTable_f89f71ee-489a-4556-8b75-5836d3f830fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LoginID
		dataType: string
		lineageTag: 31a1b967-63e3-4d94-9ece-84828319f102
		summarizeBy: none
		sourceColumn: LoginID

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 124a427c-c1e2-4bb1-9776-8017499407e9
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 509b395e-0561-431a-b3fa-dcadd4991cfc
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: 6cc3d6f9-c99d-4343-bdb6-bd3b0555fa1e
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column EmergencyContactName
		dataType: string
		lineageTag: 7e01fa9d-91e4-41d7-b16d-59dc12a3ef36
		summarizeBy: none
		sourceColumn: EmergencyContactName

		annotation SummarizationSetBy = Automatic

	column EmergencyContactPhone
		dataType: string
		lineageTag: c13aeb4b-fa4d-4b54-9741-9bd2b60b1758
		summarizeBy: none
		sourceColumn: EmergencyContactPhone

		annotation SummarizationSetBy = Automatic

	column SalariedFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 466175c9-44ec-4d5f-aa9b-282b576ceb7b
		summarizeBy: none
		sourceColumn: SalariedFlag

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: a9aef72f-d1fc-4b07-bdf9-893d871ae0dc
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column PayFrequency
		dataType: int64
		formatString: 0
		lineageTag: d769fc18-ef81-4ace-95f4-7a362e474f14
		summarizeBy: sum
		sourceColumn: PayFrequency

		annotation SummarizationSetBy = Automatic

	column BaseRate
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f17b09a3-05b1-48ae-8e79-9757377f107b
		summarizeBy: sum
		sourceColumn: BaseRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column VacationHours
		dataType: int64
		formatString: 0
		lineageTag: 968e8d4e-1d5b-4bf3-b545-7dffcb732fb5
		summarizeBy: sum
		sourceColumn: VacationHours

		annotation SummarizationSetBy = Automatic

	column SickLeaveHours
		dataType: int64
		formatString: 0
		lineageTag: 9c2b2d3a-2d13-43fb-9177-0191fccfd0a4
		summarizeBy: sum
		sourceColumn: SickLeaveHours

		annotation SummarizationSetBy = Automatic

	column CurrentFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 31cbb95e-c7ab-40be-b7a6-b76b58db2d49
		summarizeBy: none
		sourceColumn: CurrentFlag

		annotation SummarizationSetBy = Automatic

	column SalesPersonFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 09f762e7-b502-4952-bff2-dd8a559f0717
		summarizeBy: none
		sourceColumn: SalesPersonFlag

		annotation SummarizationSetBy = Automatic

	column DepartmentName
		dataType: string
		lineageTag: f279295f-d120-4439-8208-466a3d028d9d
		summarizeBy: none
		sourceColumn: DepartmentName

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 248c4493-3cba-4764-a3e9-5456017e4e7b
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: 7b2dce33-0514-4960-861e-005b3e0f4d91
			defaultHierarchy: LocalDateTable_0b419051-9042-4a48-a6fd-590cca3d58bf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b582ba53-b518-4535-873a-0df4a504a6bf
		summarizeBy: none
		sourceColumn: EndDate

		variation Variation
			isDefault
			relationship: e1f6a3fa-7166-4154-888b-00679237a293
			defaultHierarchy: LocalDateTable_c9f29703-9ceb-4c9d-a9d6-f869464506fb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 5134b185-c4ca-4380-9ecf-2555f4862673
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition DimEmployee = m
		mode: import
		source =
				let
				  Source = Sql.Database("pragmaticworkspublic.database.windows.net", "AdventureWorksDW"),
				  #"Navigation 1" = Source{[Schema = "dbo", Item = "DimEmployee"]}[Data],
				  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"FactSalesQuota", "FactResellerSales", "DimSalesTerritory", "DimEmployee(ParentEmployeeKey)", "DimEmployee(EmployeeKey)", "EmployeePhoto"})
				in
				  #"Removed columns"

	annotation PBI_ResultType = Table

